<a href="https://colab.research.google.com/github/Feruz2/Machine-learning/blob/main/Checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [3]:
import itertools

List = ['A','B','C']

for comb in itertools.combinations(List,2):
  print(comb)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [7]:
import itertools

List = ['Python', 'is', 'fun']

cycle = itertools.cycle(List)
start, end = 0, 10

for output in cycle:
  if start == end:
    break

  start += 1
  print(output)


Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [14]:
import glob

all_files = glob.glob("*.py")

for file in all_files:
    print(file)

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [2]:
from bs4 import BeautifulSoup

def extract_paragraph_text(html_content):

    soup = BeautifulSoup(html_content, 'html.parser')

    paragraph_tag = soup.find('p')

    paragraph_text = paragraph_tag.get_text() if paragraph_tag else None

    return paragraph_text

html_content = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

paragraph_text = extract_paragraph_text(html_content)
print(paragraph_text)

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [7]:
import re
import re

def replace_word_in_html(html_content):

    pattern = r'\bAI\b'

    replaced_html = re.sub(pattern, 'Artificial Intelligence', html_content)

    return replaced_html

    return replaced_text



html_content = "Welcome to AI is transforming the world"

replaced_html = replace_word_in_html(html_content)
print(replaced_html)


Welcome to Artificial Intelligence is transforming the world


**CP6**: Create a numpy array of 10 zeros.

In [16]:
import numpy as np

array = np.zeros((10))
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [18]:
import numpy as np

array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [20]:
import numpy as np

array = np.arange(9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

Machine learning models require large amounts of data because they need to learn from examples. The more examples a model has, the better it can learn to generalize to new data. This is because the model can learn to identify patterns in the data that are common to all of the examples.


For a data to be referred as large it typically refers to a dataset that is too large to be processed or analyzed using traditional methods like spreadsheets or text processors.Generally, a "large" amount of data implies that the dataset contains a substantial number of samples or instances. The specific number can vary, but it often implies having thousands or even millions of data points





```
# This is formatted as code
```

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

1)Adversarial attacks through advesrial examples: Adversarial examples are inputs that are designed to fool AI models. These inputs are typically very small changes to legitimate inputs, but they can cause AI models to make incorrect predictions.Adversarial attacks can be used to deceive AI-powered security systems, spam filters, or even autonomous vehicles. Adversaries may exploit vulnerabilities in AI algorithms to manipulate or bypass their intended functionality.

Prevention: To mitigate adversarial attacks, researchers and practitioners are working on developing robust and resilient AI models. Techniques such as adversarial training, where models are trained using both regular and adversarial examples, can improve their ability to withstand such attacks.

2)Privacy and Surveillance:
AI technologies, particularly in the realm of surveillance and data analysis, can infringe upon individuals' privacy rights. Advances in facial recognition, tracking algorithms, and data aggregation can lead to intrusive surveillance practices. Adversaries can misuse AI-powered surveillance systems to invade privacy, track individuals without consent, or conduct mass surveillance without appropriate safeguards.

Prevention: Protecting privacy in the context of AI requires robust data protection laws, privacy regulations, and ethical guidelines. Implementing privacy-enhancing techniques, such as differential privacy, can help anonymize and protect sensitive data. Strong encryption and secure storage practices can safeguard personal information. Additionally, ensuring transparency and consent in data collection and usage can empower individuals to control their personal information and mitigate privacy risks.


